import React,{useEffect,useMemo,useState} from 'react';
import {BackHandler,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View,Image,ScrollView} from 'react-native';
import {JellyfinApi,JItem,JellyfinAuth} from './api/jellyfin';

const C={bg:'#101010',panel:'#181818',panel2:'#242424',text:'#fff',muted:'#b9b9b9',accent:'#00a4dc'};
const store:any=globalThis as any;

function Card({item,onPress,api,wide=false}:{item:JItem;onPress:()=>void;api:JellyfinApi;wide?:boolean}){return <Pressable hasTVPreferredFocus={false} onPress={onPress} style={({focused})=>[styles.card,focused&&styles.focus]}><Image source={{uri:api.image(item.Id)}} style={wide?styles.backdrop:styles.poster}/><Text numberOfLines={1} style={styles.cardTitle}>{item.Name}</Text></Pressable>}
function Rail({title,items,api,onItem,wide=false}:{title:string;items:JItem[];api:JellyfinApi;onItem:(x:JItem)=>void;wide?:boolean}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{items.map(x=><Card key={x.Id} item={x} api={api} onPress={()=>onItem(x)} wide={wide}/>)}</ScrollView></View>}

export default function App(){
 const [auth,setAuth]=useState<JellyfinAuth|null>(null); const [login,setLogin]=useState(false); const [server,setServer]=useState(''); const [user,setUser]=useState(''); const [pass,setPass]=useState(''); const [error,setError]=useState(''); const [view,setView]=useState('home'); const [items,setItems]=useState<JItem[]>([]); const [libraries,setLibraries]=useState<JItem[]>([]); const [selected,setSelected]=useState<JItem|null>(null); const [query,setQuery]=useState('');
 const api=useMemo(()=>auth?new JellyfinApi(auth):null,[auth]);
 useEffect(()=>{const saved=store.localStorage?.getItem?.('jfv-auth');if(saved)try{setAuth(JSON.parse(saved))}catch{}},[]);
 useEffect(()=>{if(!api)return;api.views().then(r=>setLibraries(r.Items||[])).catch(e=>setError(e.message));api.items('SortBy=DateCreated&SortOrder=Descending&IncludeItemTypes=Movie,Series,Episode&Recursive=true&Fields=Overview,ProductionYear,RunTimeTicks&Limit=24').then(r=>setItems(r.Items||[])).catch(e=>setError(e.message))},[api]);
 const doLogin=async()=>{try{setError('');const a=await new JellyfinApi({server,token:'',user:{}} as any).authenticate(server,user,pass);const next={server:server.replace(/\\/$/,''),token:a.AccessToken,user:a.User};setAuth(next);try{store.localStorage?.setItem?.('jfv-auth',JSON.stringify(next))}catch{}}catch(e:any){setError(e.message)}};
 if(!auth||login)return <SafeAreaView style={styles.screen}><View style={styles.login}><Text style={styles.logo}>Jellyfin</Text><Text style={styles.sub}>Vega TV</Text><TextInput autoFocus style={styles.input} placeholder="Server-Adresse" placeholderTextColor={C.muted} value={server} onChangeText={setServer}/><TextInput style={styles.input} placeholder="Benutzername" placeholderTextColor={C.muted} value={user} onChangeText={setUser}/><TextInput secureTextEntry style={styles.input} placeholder="Passwort" placeholderTextColor={C.muted} value={pass} onChangeText={setPass}/><Pressable hasTVPreferredFocus onPress={doLogin} style={({focused})=>[styles.button,focused&&styles.focus]}><Text style={styles.buttonText}>ANMELDEN</Text></Pressable>{!!error&&<Text style={styles.error}>{error}</Text>}</View></SafeAreaView>;
 const openItem=async(x:JItem)=>{try{const full=await api!.item(x.Id);setSelected(full)}catch(e:any){setError(e.message)}};
 if(selected)return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.detail}><Image source={{uri:api!.image(selected.Id)}} style={styles.detailPoster}/><View style={styles.detailText}><Text style={styles.detailTitle}>{selected.Name}</Text><Text style={styles.meta}>{selected.ProductionYear||''}  {selected.Type}</Text><Text style={styles.overview}>{selected.Overview||''}</Text><Pressable hasTVPreferredFocus onPress={()=>{}} style={({focused})=>[styles.button,focused&&styles.focus]}><Text style={styles.buttonText}>▶  ABSPIELEN</Text></Pressable><Pressable onPress={()=>setSelected(null)}><Text style={styles.back}>Zurück</Text></Pressable></View></ScrollView></SafeAreaView>;
 const content=view==='home'?<><Rail title="Zuletzt hinzugefügt" items={items} api={api!} onItem={openItem}/><Rail title="Bibliotheken" items={libraries} api={api!} onItem={openItem}/></>:view==='search'?<><Text style={styles.heading}>Suche</Text><TextInput autoFocus style={styles.search} placeholder="Titel suchen…" placeholderTextColor={C.muted} value={query} onChangeText={async q=>{setQuery(q);if(q.length>1){const r=await api!.items('SearchTerm='+encodeURIComponent(q)+'&Recursive=true&IncludeItemTypes=Movie,Series,Episode&Fields=Overview,ProductionYear&Limit=50');setItems(r.Items||[])}}}/><Rail title="Ergebnisse" items={items} api={api!} onItem={openItem}/></>:<Rail title="Bibliotheken" items={libraries} api={api!} onItem={openItem}/>;
 return <SafeAreaView style={styles.screen}><View style={styles.header}><Text style={styles.logoSmall}>Jellyfin</Text><Pressable onPress={()=>setView('home')} style={({focused})=>[styles.nav,focused&&styles.focus]}><Text style={styles.navText}>Start</Text></Pressable><Pressable onPress={()=>setView('libraries')} style={({focused})=>[styles.nav,focused&&styles.focus]}><Text style={styles.navText}>Bibliotheken</Text></Pressable><Pressable onPress={()=>setView('search')} style={({focused})=>[styles.nav,focused&&styles.focus]}><Text style={styles.navText}>Suche</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}>{content}</ScrollView>{!!error&&<Text style={styles.errorBar}>{error}</Text>}</SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},header:{height:78,backgroundColor:'#0c0c0c',flexDirection:'row',alignItems:'center',paddingHorizontal:45,gap:12},logo:{fontSize:42,fontWeight:'800',color:C.text},logoSmall:{fontSize:30,fontWeight:'800',color:C.text,marginRight:25},sub:{fontSize:20,color:C.muted,marginBottom:25},nav:{paddingHorizontal:22,paddingVertical:13,borderRadius:7},navText:{color:C.text,fontSize:18},content:{padding:34,paddingHorizontal:48},section:{marginBottom:34},sectionTitle:{fontSize:25,fontWeight:'700',color:C.text,marginBottom:15},rail:{gap:17},card:{width:180,marginRight:2,borderRadius:8,paddingBottom:4},poster:{width:180,height:270,borderRadius:7,backgroundColor:C.panel},backdrop:{width:280,height:158,borderRadius:7,backgroundColor:C.panel},cardTitle:{color:C.text,fontSize:16,fontWeight:'600',marginTop:7},focus:{backgroundColor:C.accent,transform:[{scale:1.04}]},login:{width:620,alignSelf:'center',marginTop:90,padding:45,backgroundColor:C.panel,borderRadius:12},input:{height:55,borderRadius:7,borderWidth:1,borderColor:'#444',backgroundColor:'#101010',color:C.text,paddingHorizontal:16,fontSize:18,marginVertical:8},button:{backgroundColor:C.accent,paddingVertical:15,paddingHorizontal:24,borderRadius:7,alignSelf:'flex-start',marginTop:14},buttonText:{fontWeight:'800',fontSize:17,color:'#fff'},error:{color:'#ff7373',marginTop:15,fontSize:16},errorBar:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#421818',color:'#fff',padding:12,textAlign:'center'},detail:{padding:55,flexDirection:'row',gap:45},detailPoster:{width:300,height:450,borderRadius:8},detailText:{flex:1,paddingTop:10},detailTitle:{fontSize:38,fontWeight:'800',color:C.text},meta:{color:C.muted,fontSize:18,marginVertical:12},overview:{fontSize:20,lineHeight:30,color:'#ddd',maxWidth:900},back:{color:C.text,fontSize:18,marginTop:25},heading:{fontSize:36,fontWeight:'800',color:C.text,marginBottom:18},search:{height:56,borderRadius:8,borderWidth:1,borderColor:'#444',backgroundColor:C.panel,color:C.text,fontSize:20,paddingHorizontal:18,marginBottom:25}});
